name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - develop

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.5
        build_only: true
